=pipeline {
    agent any
    
    environment {
        releaseName = 'my-release'
        chartName = 'webapp'
        chartVersion = '1.2.3'
    }
    stages {
        stage{
            steps {
                git 'https://github.com/lijitijil/ProjectDeploy.git'
'
            }
        }
        stage('Check Helm Version') {
            steps {
                sh 'helm version'
            }
        }
        
        stage('Install or Upgrade Helm Chart') {
            steps {
                 sh 'helm install teckask webapp'
                    }
                }
             }
}
