=pipeline {
    agent any
    
    environment {
        releaseName = 'my-release'
        chartName = 'webapp'
        chartVersion = '1.2.3'
    }
    stages {
        stage{
            steps {
                git 'https://github.com/ARUNBABU99/SAMPLE_PROJECT_DEVOPS.git'
            }
        }
        stage('Check Helm Version') {
            steps {
                sh 'helm version'
            }
        }
        
        stage('Install or Upgrade Helm Chart') {
            steps {
                script {
                    def releaseExists = sh(returnStatus: true, script: "helm status ${releaseName} >/dev/null 2>&1")
                    
                    if (releaseExists == 0) {
                        sh "helm upgrade ${releaseName} ${chartName} --version ${chartVersion}"
                    } else {
                        sh "helm install ${releaseName} ${chartName} --version ${chartVersion}"
                    }
                }
            }
        }
    }
}
